# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 292a63d0fc3bccab9e58a925db556b05a4c8030a04db6a4a8f4e69d7c6882e3b7fd7f5f2896cff3f3c02b51e4b366276785e03843091c55c1ccf499c967f29a3

test:
  secret_key_base: 4725f7c1293b1952d7c0d0942c7d9fa6ae3e968dcf467dc0d0671aa19810cb8ae324b3e2b856a302187b67102ecc451c205ce0ba587e364d7166abdaa7404892

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
